nixpacks.toml - Railway Java 17 configuration
[phases.setup]
nixPkgs = ["openjdk17", "gradle"]

[phases.build]
cmds = ["./gradlew clean build -x test -x check"]

[start]
cmd = "java -jar build/libs/geolocation-api.jar"

[variables]
JAVA_VERSION = "17"